server:
  port: 8003

spring:
  application:
    name: microServiceCloudProviderDept

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_db3
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: net.biancheng.c
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: spring-cloud-provider-8003
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app.name: micro-service-cloud-provider-dept
  company.name: c.biancheng.net
  build.aetifactId: @project.artifactId@
  build.version: @project.version@